version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../projfrontend
      dockerfile:  Dockerfile
    ports:
      - 3000:3000
    

  mongodb:
    image: mongo
    # ports:
    #   - 27017:27017